import 'package:courtify/core/error/failures.dart';
import 'package:courtify/domain/entities/booking.dart';
import 'package:courtify/domain/repositories/i_booking_repository.dart';

class MakeBookingUseCase {
  final IBookingRepository repository;

  MakeBookingUseCase(this.repository);

  Future<Booking> execute({
    required int userId,
    required int courtId,
    required int slotId,
    required DateTime bookDate,
    required String startTime,
    required String endTime,
    required double totalPrice,
    required DateTime currentTime,
  }) async {
    // 1. Validation logic
    final timeParts = startTime.split(':');
    final startHour = int.parse(timeParts[0]);
    final startMinute = int.parse(timeParts[1]);

    final playStart = DateTime(
      bookDate.year, bookDate.month, bookDate.day, 
      startHour, startMinute
    );

    // BR-C5: Cannot book past slots.
    if (playStart.isBefore(currentTime)) {
      throw ValidationFailure("BR-C5: Cannot book slots in the past.");
    }

    // BR-C8: Customer cannot create overlapping bookings
    final hasOverlap = await repository.hasOverlappingBooking(
      courtId: courtId,
      bookDate: bookDate,
      startTime: startTime,
      endTime: endTime,
    );

    if (hasOverlap) {
      throw ValidationFailure("BR-C8: The selected time slot is already booked or locked.");
    }

    // Create new entity (ID will be generated by DB)
    final booking = Booking(
      id: 0, 
      userId: userId,
      totalPrice: totalPrice,
      status: BookingStatus.pending,
      paymentStatus: PaymentStatus.unpaid,
      createdAt: currentTime,
      slots: [], 
    );

    // Save and return
    return await repository.createBooking(booking, slotId);
  }
}
